### PR TITLE
Csv

### PR DESCRIPTION
**Pull request by YoungFaithful**
Adressing #14

### CODE REVIEW

**Comment by YoungFaithful** [comment]
I didn't check in the newest documentation in the first commit (still had an older CSV version on my local mashine) and it didn't throw any warning, so I thought optional is enough...

**Review by holgerteichgraeber — CHANGES_REQUESTED** [review]
There is a typo in strict

**Comment by YoungFaithful** [comment]
> There is a typo in strict

Oh yeah...

**Comment by holgerteichgraeber** [comment]
#19 was to master, so changed branch of this one to master too.

**Pull request merged**
