### PR TITLE
Dev to master

### PR DESCRIPTION
**Pull request by holgerteichgraeber**
I realized that the master branch still relies on ClustForOpt and has not been updated for a while. 
There have been new students potentially interested in CapacityExpansion, and I think it would be nice to have them use an up-to-date version. 

After having worked on the dev branch for a week, I feel like it is stable enough to go to master. 

How about we make the cut before merging #37 , and that can then be part of the next merge to master?

### CODE REVIEW

**Comment by holgerteichgraeber** [comment]
Merge #40 into dev before merging this PR to update version number.

**Review by YoungFaithful — APPROVED** [review]

**Comment by YoungFaithful** [comment]
And we edit the branch for the Documentation later on?

**Comment by holgerteichgraeber** [comment]
> 
> 
> And we edit the branch for the Documentation later on?

Good point, what needs to be done for the documentation? I think that could be 0.2.1 then..

**Comment by holgerteichgraeber** [comment]
#41 NEWS.md opened to document breaking changes.

**Pull request merged**
