### PR TITLE
Jump

### PR DESCRIPTION
**Pull request by YoungFaithful**
Updated JuMP to `v0.20`

### CODE REVIEW

**Comment by YoungFaithful** [comment]
Addressing #25

**Review by holgerteichgraeber — APPROVED** [review]
Sweet, thanks for enabling that. Checks seem to fail.

**Comment by YoungFaithful** [comment]
> Sweet, thanks for enabling that. Checks seem to fail.

It's a little weird: All variables, except the costs match exactly after switching JuMP. I suppose it is a different default value, communiacting with Clp or so. I'll double check, before merging and ensure that tests will run.

**Review by YoungFaithful — COMMENTED** [review]
Done

**Pull request merged**
