### PR TITLE
Compatability update for ClustForOpt 0.4.0

### PR DESCRIPTION
**Pull request by holgerteichgraeber**
- Updated structs from ClustForOpt 
- Somehow the test case with multiple nodes fails on my personal machine. Can you have a look, I do not know why?

### CODE REVIEW

**Comment by YoungFaithful** [comment]
The problem is that some values in GER_18 are not met exactly. I'll try to find the reason for that.

**Comment by YoungFaithful** [comment]
Mir scheint, als wäre das wieder das Zuordnungsproblem in ClustForOpt: wird einfach nur PV an einer Stelle und Trassen ausgebaut...
image

**Comment by holgerteichgraeber** [comment]
> 
> 
> Mir scheint, als wäre das wieder das Zuordnungsproblem in ClustForOpt: wird einfach nur PV an einer Stelle und Trassen ausgebaut...
> image

How did we fix that last time, I though we took care of that by use of arrays? 
I am surprised because generally all this commit did was change the naming of `best_result` to `clust_data`, I don't see a connection there.

**Comment by YoungFaithful** [comment]
I will rerun the tests as soon as bug is merged in ClustForOpt

**Comment by holgerteichgraeber** [comment]
@YoungFaithful  the tests on the 18 node system still fail. Any idea why?

**Comment by YoungFaithful** [comment]
I think we may have to wait until the new version is registered...

**Comment by holgerteichgraeber** [comment]
Nice, it passed after version 0.4.1 of ClustForOpt was registered.

**Pull request merged**
